### ISSUE TITLE
Can not shorten IP

### ISSUE THREAD

**Issue by poeti8** [thedevs-network/kutt-extension#110]
Can not create short URLs for IPs. it is considered as valid URL on Kutt API but the extension does not allow it.

**Comment by abhijithvijayan** [comment]
@poeti8 the current validation was done to avoid shortening internal browser URLs(`chrome://flags`)
i will keep the server side validation as such for the client.

**Comment by abhijithvijayan** [comment]
@poeti8 fixed in f94479e9a9af9ddd41d5cc85ffcb44bdbd9ff422

**Comment by abhijithvijayan** [comment]
can be released in the next feature release
