### ISSUE TITLE
[BUG] Firefox Link Broken

### ISSUE THREAD

**Issue by creyD** [thedevs-network/kutt-extension#134]
The firefox extension is apparently removed or outdated? When clicking on the link on the homepage it gives a 404 and in the extensions directory I can't seem to find it.

**Comment by battosai30** [comment]
No news about this ?

**Comment by djoris** [comment]
It has been removed due to their security policy, updates on that are in ticket #127

**Comment by creyD** [comment]
Ok so this is a duplicate, we can close it as such. However as the other ticket is open for more than a year now, I would suggest at least adding a hint on the website that the links are broken.
