### ISSUE TITLE
Firefox custom domains not showing up

### ISSUE THREAD

**Issue by LeonPro12** [thedevs-network/kutt-extension#98]
I have a custom domain set up. When I use the Firefox extension it does show up as a blank url (it works when I selected).

**Comment by abhijithvijayan** [comment]
Could you send me a token and custom domain set up

**Comment by LeonPro12** [comment]
> 
> 
> Could you send me a token and custom domain info and possibly a png clip of the behaviour?

How? Via E-Mail?

**Comment by abhijithvijayan** [comment]
Attach the png clip here.

**Comment by abhijithvijayan** [comment]
@LeonPro12 ^^
